/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 618062
 */
public class ConfirmationFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmationFrame
     */
    
    MenuFrame mainTable; //Stores frame for hash table
    AddLoc locationEditor; //Frame for editing locations
    String location; //Location string
    EditEmployeeFrame empEditor; //Frame for editing employees
    boolean invalid; //Random variable
    MyHashTable hT; //refval for hash table
    int eNum; //emp num
    int newENum;
    EmployeeInfo eTA; //empToAdd
    
    
    
    public ConfirmationFrame(MenuFrame main) { //Constructor for when removing employees
        mainTable = main;
        main.setEnabled(false);
        initComponents();
    }
    
    public ConfirmationFrame(AddLoc loc, String toEdit) { //Construtor for editing lcoations
        location = toEdit;
        locationEditor = loc;
        locationEditor.setEnabled(false);
        initComponents();
        jLabel1.setText("Do you want to delete the selected location?");
    }
    
    public ConfirmationFrame(EditEmployeeFrame empEdit,MyHashTable haT, int eN, int newEN, EmployeeInfo empToAdd) { //Constructor for editing employees
        empEditor = empEdit;
        empEditor.setEnabled(false);
        hT =haT;
        eNum = eN;
        newENum = newEN;
        eTA = empToAdd;
        initComponents();
        jLabel1.setText("Do you want to continue with these changes?");
        invalid = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Do you want to delete the selected employees?");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        // TODO add your handling code here:
        //Simply returns to original frame without performing changes
        if (mainTable != null) { 
            MainJFrame.setMenuLabel(false);
            mainTable.setEnabled(true);
        }
        if (locationEditor != null) {
            locationEditor.labelOff();
            locationEditor.setEnabled(true);
        }
        if (empEditor != null) {
            empEditor.valid = true;
            empEditor.setEnabled(true);
            invalid = true;
            empEditor.setDone("Submit");
            
        }
        this.dispose();
    }//GEN-LAST:event_noButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
        //Performs changes and returns
        if (mainTable != null) {
            MainJFrame.setMenuLabel(false);
            mainTable.removeEmployees();
            mainTable.setEnabled(true);
        }
        if (locationEditor != null) {
            locationEditor.removeLocation(location);
            locationEditor.setEnabled(true);
        }
        if (empEditor != null) {
            hT.removeFromTable(eNum);
            eTA.setEmployeeNumber(newENum);
            hT.addToTable(eTA);
            empEditor.done = true;
            empEditor.setEnabled(true);
            empEditor.setDone("Done");
            
        }
        this.dispose();
    }//GEN-LAST:event_yesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmationFrame(new MenuFrame(false)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton noButton;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
